# Generated by Django 5.1.1 on 2024-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
